AllCops:
  TargetRubyVersion: 2.4

Gemspec/OrderedDependencies:
  Exclude:
    - fakepay.gemspec

Metrics/AbcSize:
  Exclude:
    - lib/fakepay/commands/create.rb

Metrics/MethodLength:
  Exclude:
    - lib/**/*.rb

Metrics/BlockLength:
  Exclude:
    - fakepay.gemspec
    - spec/**/*.rb
